[package]
name = "groth16_framework"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytes = "1.5"
ethereum-types = "0.14"
hex = "0.4"
log = "0.4"
plonky2 = { version = "0.1.4" }
plonky2x = { git = "https://github.com/Lagrange-Labs/succinctx", branch = "lagrange" }
revm = { version = "3.5", default-features = false }
rlp = "0.5"
sha3 = "0.10"

[dev-dependencies]
mapreduce-plonky2 = { path = "../mapreduce-plonky2" }
plonky2_ecgfp5 = { git = "https://github.com/Lagrange-Labs/plonky2-ecgfp5" }
rand = "0.8"
serial_test = "3.0"
