[package]
name = "recursion-framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
log = "0.4.20"
plonky2 = { version = "0.1.4" }

[dev-dependencies]
rstest = "0.18.2"
serial_test = "3.0.0"

