[package]
name = "mapreduce-plonky2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
itertools = "0.12.0"
ethers = { version ="2.0.11", default-features = false, features = ["rustls"]}
plonky2 = { version = "0.1.4" }

# supporting latest plonky2
plonky2_crypto = { git = "https://github.com/nikkolasg/plonky2-crypto" , branch = "feat/serialization" }
plonky2-bn254 = { git = "https://github.com/nikkolasg/plonky2-bn254" }
plonky2_ecdsa = { git = "https://github.com/nikkolasg/plonky2-ecdsa" }
rand = "0.8.5"
serde = "1.0.193"
# TODO: see if we can revert to upstream repo: originally used 
# to fetch proof with "node" instead of already encoded struct
eth_trie = { git = "https://github.com/nikkolasg/eth-trie.rs" }
rlp = "0.5.2"
sha3 = "0.10.8"
bincode = "1.3.3"
hashbrown = "0.14.3"
log = "0.4.14"
env_logger = "0.9.0"

[dev-dependencies]
anyhow = "1.0.75"
csv = "1.3.0"
hex = "0.4.3"
itertools = "0.12.0"
rlp = "0.5.2"
rmp-serde = "1.1.2"
serde_json = "1.0.108"
sha3 = "0.10.8"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
env_logger = { version = "0.9.0", default-features = false }
log = { version = "0.4.14", default-features = false }
rand = "0.8.5"
ark-bn254 = "0.4.0"
ark-std = "0.4.0"

[features]
ci = []

[patch.crates-io]
plonky2 = { git = "https://github.com/nikkolasg/plonky2" }

#[patch."https://github.com/nikkolasg/plonky2-bn254"]
#plonky2-bn254 = { path = "../plonky2-bn254" }