[package]
name = "inspect"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
hex.workspace = true
itertools.workspace = true
serde.workspace = true
serde_json.workspace = true


bb8 = "0.8.5"
bb8-postgres = "0.8.1"
clap = { version = "4.5.17", features = ["derive"] }
colored = "2.1.0"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
postgres-types = {version =  "0.2.6", features = ["with-serde_json-1"] }
tabled = { version = "0.16.0", features = ["ansi"] }
tokio = { version = "1.34", features = ["sync", "macros"], default-features = false }
tokio-postgres = { version = "0.7.10", features = ["with-chrono-0_4"] }

ryhope = { path = "../ryhope" }
mp2_v1 = { path = "../mp2-v1" }
