[package]
name = "inspect"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
hex.workspace = true
itertools.workspace = true
serde.workspace = true

clap = { version = "4.5.17", features = ["derive"] }
colored = "2.1.0"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
tabled = { version = "0.16.0", features = ["ansi"] }
tokio = { version = "1.34", features = ["sync", "macros"], default-features = false }

ryhope = { path = "../ryhope" }
mp2_v1 = { path = "../mp2-v1" }
