[package]
name = "ryhope"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
delegate = "0.12.0"
itertools.workspace = true
log.workspace = true
postgres = { version = "0.19.7", features = ["with-serde_json-1"] }
serde.workspace = true

[dev-dependencies]
rand = "0.8.5"
sha256 = { version = "1.5.0", default-features = false }
