[package]
name = "verifiable-db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
log.workspace = true
plonky2.workspace = true
mp2_common = { path = "../mp2-common" }
mp2_test = { path = "../mp2-test" }
plonky2_ecgfp5.workspace = true
rand.workspace = true
ethers.workspace = true
serde.workspace = true
derive_more = "0.99.18"
mp2_v1 = { path = "../mp2-v1" }
recursion_framework =  { path = "../recursion-framework" }
