[package]
name = "verifiable-db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
log.workspace = true
plonky2.workspace = true
itertools.workspace = true
mp2_common = { path = "../mp2-common" }

[dev-dependencies]
mp2_test = { path = "../mp2-test" }
