[profile.default]
src = "mp2-v1/test-contracts/src"
out = "mp2-v1/test-contracts/out"
broadcast = "mp2-v1/test-contracts/broadcast"
script = "mp2-v1/test-contracts/script"
libs = ["mp2-v1/test-contracts/lib"]
optimizer = true
optimizer_runs = 200
solc-version = "0.8.24"
evm_version = "cancun"
verbosity = 4

[fmt]
line_length = 80

[rpc_endpoints]
local = "http://localhost:8545"
