[package]
name = "mp2_v1"   # TODO: fix the name to a meaningful one.
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bincode.workspace = true
env_logger.workspace = true
eth_trie.workspace = true
hashbrown.workspace = true
alloy.workspace = true
itertools.workspace = true
log.workspace = true
paste.workspace = true
plonky2.workspace = true
plonky2_crypto.workspace = true
plonky2_ecgfp5.workspace = true
rand.workspace = true
rlp.workspace = true
ryhope.workspace = true
serde.workspace = true
serde_arrays.workspace = true
sha3.workspace = true

mp2_common = { path = "../mp2-common" }
verifiable-db = { path = "../verifiable-db" }
recursion_framework = { path = "../recursion-framework" }

[dev-dependencies]
alloy.workspace = true
csv.workspace = true
hex.workspace = true
rmp-serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
serial_test.workspace = true

mp2_test = { path = "../mp2-test" }
envconfig = "0.10.0"
test-log = "0.2.16"
jammdb = "0.11.0"
