[package]
name = "mp2_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
eth_trie.workspace = true
hashbrown.workspace = true
log.workspace = true
plonky2.workspace = true
rand.workspace = true

recursion_framework = { path = "../recursion-framework" }

[features]
ci = []
