name: Manually Publish PPs
on:
  workflow_dispatch:

jobs:
  public-params:
    name: Manually Generate & Upload PPs, hash-indexed
    runs-on: ['memory:64GB']
    environment: CI
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-11-09
      - name: Check aws is installed
        run: aws --version
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20' # The Go version to download (if necessary) and use.
      - name: Generate PPs
        run: |
          ulimit -s unlimited
          cargo run --release --bin gen-params --mode hash
      - name: Upload PPs
        run: aws s3 cp --no-progress --recursive zkmr_params s3://lagrange-public-parameters --endpoint-url=https://428e47101872e479a0c311b576430fac.r2.cloudflarestorage.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CF_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eeur
