name: Manually Publish PPs
on:
  workflow_dispatch:
    inputs:
      mode:
        description: Save params under major version or git hash
        required: true
        type: choice
        options:
          - hash
          - major

jobs:
  public-params:
    name: Manually Generate & Upload PPs, hash-indexed
    runs-on: ['nix-128g']
    environment: CI
    steps:
      - uses: actions/checkout@v4
      - name: Generate PPs
        shell: devenv shell bash -- -e {0}
        run: |
          ulimit -s unlimited
          cargo run --release --bin gen-params -- --mode ${{ inputs.mode }}
      - name: Upload PPs
        shell: devenv shell bash -- -e {0}
        run: tools/upload-s3.pl zkmr_params
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CF_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eeur
