on:
  pull_request:
  push:
    branches:
      - main


name: Check, Test, and Format

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 'nightly-2025-05-22'
          components: rustfmt,clippy
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: check
        run: cargo check --all --tests
      - name: clippy
        run: cargo clippy --all-targets --all -- -D warnings
      - name: fmt
        run: cargo fmt --all -- --check

  test:
    name: Test Suite
    runs-on: ['nix-128g']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Generate a random port number
        run: echo PGSQL_PORT=$(shuf -i 5000-30000 -n1) > .env
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Put cargo in PATH
        shell: devenv shell bash -- -e {0}
        run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
      - name: Run cargo test
        run: devenv test
        env:
          RUST_LOG: "info"
          RUST_MIN_STACK: 10485760
          CI_RPC_URL: ${{ secrets.CI_RPC_URL }}
          CI_SEPOLIA: ${{ secrets.CI_SEPOLIA }}
          CI_ETH: ${{ secrets.CI_ETH }}
          LPN_PARAMS_DIR: $HOME/ci_params/
          LPN_PARAMS_REBUILD: "true"
