on:
  pull_request:
  push:
    branches:
      - main


name: Check, Test, and Format

jobs:
  fmt:
    name: Rustfmt
    runs-on: ['memory:8GB']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install devenv
        run: |
          if [ -e /nix/var/nix/profiles/default/bin/nix-env ]
          then
              /nix/var/nix/profiles/default/bin/nix-env -if https://github.com/cachix/devenv/tarball/latest
          else
              nix-env -if https://github.com/cachix/devenv/tarball/latest
          fi

          echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH
      - name: Run cargo test
        shell: devenv shell bash -- -e {0}
        run: cargo fmt --all -- --check

  check:
    name: Check
    runs-on: ['memory:8GB']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install devenv
        run: |
          if [ -e /nix/var/nix/profiles/default/bin/nix-env ]
          then
              /nix/var/nix/profiles/default/bin/nix-env -if https://github.com/cachix/devenv/tarball/latest
          else
              nix-env -if https://github.com/cachix/devenv/tarball/latest
          fi

          echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH
      - name: Run cargo check
        shell: devenv shell bash -- -e {0}
        run: cargo check --tests

  test:
    name: Test Suite
    runs-on: ['nix-128g']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Generate a random port number
        run: echo PGSQL_PORT=$(shuf -i 5000-30000 -n1) > .env
      - name: Install foundry
        shell: devenv shell bash -- -e {0}
        run: cargo install --root ${HOME}/.cargo --git https://github.com/foundry-rs/foundry --rev c4a984f forge anvil
      - name: Put cargo in PATH
        shell: devenv shell bash -- -e {0}
        run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
      - name: Run cargo test
        run: devenv test
        env:
          RUST_LOG: "info"
          RUST_MIN_STACK: 10485760
          CI_RPC_URL: ${{ secrets.CI_RPC_URL }}
          CI_SEPOLIA: ${{ secrets.CI_SEPOLIA }}
          CI_ETH: ${{ secrets.CI_ETH }}
          LPN_PARAMS_DIR: $HOME/ci_params/
          LPN_PARAMS_REBUILD: "true"
